server:
  port: 3049
spring:
  ##replicationStatus: UNPROCESSED
  #transactionStatus: UNPROCESSED
  jmx:
    default-domain: FinFlowz-Batch
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
  batch:
    initialize-schema: always
  application:
    name: FinFlowz-Batch
  banner:
    location: classpath:banner.txt
#GLOBAL_PROPERTY_PATH : C:\FinFlowz\Properties\FinFlowz.yml
PROPERTY_PATH : C:\FinFlowz\Properties\FinFlowz-Batch.yml
#SESSION_PROPERTY_PATH : C:\FinFlowz\Properties\FinFlowz-security.yml

CRON_JOB_MICROSERVICE_BATCH: '*/10 * * * * ?'